apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: conversao
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/victormilk/web-page-deploy.git
    targetRevision: HEAD
    path: kustomize
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: conversao
    